services:
  careacross-backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        - USER_ID=1000 
        - GROUP_ID=1000
    container_name: careacross-backend
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    depends_on:
      - careacross-postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      
  careacross-postgres:
    image: postgres:16.4
    container_name: careacross-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
